SquashLeague/src/SquashLeague/Controllers/Web/AppController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using SquashLeague.Models;
using SquashLeague.Services;
using SquashLeague.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SquashLeague.Controllers.Web
{
    public class AppController : Controller
    {
        private IMailService _mailService;
        private IConfigurationRoot _config;
        private ISquashRepository _repo;
        private ILogger<AppController> _logger;

        public AppController(IMailService mailService, 
            IConfigurationRoot config, 
            SquashContext context, 
            ISquashRepository repo,
            ILogger<AppController> logger)
        {
            _mailService = mailService;
            _config = config;
            _repo = repo;
            _logger = logger;
        }

        public IActionResult Index()
        {
            try
            {
                var data = _repo.GetAllTrips();
                return View(data);
            }
            catch(Exception ex)
            {
                _logger.LogError($"Failed to get trips in Index page: {ex.Message}");
                return Redirect("/error");
            }
            
        }

        public IActionResult Contact()
        {
            
            return View();
        }

        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            if(model.Email.Contains("aol.com"))
            {
                ModelState.AddModelError("Email", "We don't support AOL addresses");
            }

            if(ModelState.IsValid)
            {
                _mailService.SendMail(_config["MailSettings:ToAddress"], model.Email, "From Squash", model.Message);

                ModelState.Clear();

                ViewBag.UserMessage = "Message Sent";
            }
            
            return View();
        }

        public IActionResult About()
        {
            return View();
        }
    }
}

SquashLeague/src/SquashLeague/Views/Shared/_Layout.cshtml
@{
    ViewBag.Title = "Home Page";
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Squash League - @ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>

    <div id="sidebar" class="container">
        <img src="~/img/squashball.png" alt="headshot" class="headshot" />
        <span id="username">Tomasz Tomaszewski</span>
        <ul class="nav">
            <li><a asp-controller="App" asp-action="Index">Home</a></li>
            <li><a asp-controller="App" asp-action="About">About</a></li>
            <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
        </ul>
    </div>

    <div id="wrapper">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <ul class="nav navbar-nav navbar-left">
                    <li>
                        <button id="sidebarToggle" class="btn btn-primary">
                            <i class="fa fa-angle-left"></i>
                        </button>
                    </li>
                </ul>
                <a asp-controller="App" asp-action="Index" class="navbar-brand">Squash League</a>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#" class="btn btn-sm btn-info">
                            <i class="fa fa-save"></i>Save
                        </a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm btn-info">
                            <i class="fa fa-print"></i>Print
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
        <div id="main" class="container-fluid">
            <div>
                @RenderBody()
            </div>
        </div>
        <div id="footer" class="container-fluid">
            <div class="navbar navbar-inverse navbar-fixed-bottom">
                <h6 class="text-center text-info">&copy; 2016 ActiveBuddy Ltd.</h6>
            </div>
        </div>
    </div>

    

    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/js/site.js"></script>

    @RenderSection("scripts", false)

</body>

</html>